spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  info
    org.springframework:  info
    org.mybatis:  ERROR
    org.linlinjava.litemall.admin:  info
    org.linlinjava.litemall:  info

swagger:
  production: false